In [2]:
import pandas as pd

In [4]:
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/'
url=f'{prefix}/yellow_tripdata_2021-01.csv.gz'

In [5]:
df=pd.read_csv(url)

/tmp/ipykernel_64105/773934961.py:1: DtypeWarning: Columns (6: store_and_fwd_flag) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(url)

In [6]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1.0,2021-01-01 00:30:10,2021-01-01 00:36:12,1.0,2.10,1.0,N,142,43,2.0,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1.0,2021-01-01 00:51:20,2021-01-01 00:52:19,1.0,0.20,1.0,N,238,151,2.0,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1.0,2021-01-01 00:43:30,2021-01-01 01:11:06,1.0,14.70,1.0,N,132,165,1.0,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1.0,2021-01-01 00:15:48,2021-01-01 00:31:01,0.0,10.60,1.0,N,138,132,1.0,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2.0,2021-01-01 00:31:49,2021-01-01 00:48:21,1.0,4.94,1.0,N,68,33,1.0,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [7]:
len(df)

1369765

In [22]:
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

df = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates
)

In [24]:
len(df)

1369765

In [11]:
!uv add sqlalchemy

Resolved 115 packages in 608ms
Prepared 1 package in 82ms
░░░░░░░░░░░░░░░░░░░░ [0/1] Installing wheels...                                 warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 1 package in 76ms
 + sqlalchemy==2.1.3

In [13]:
!uv add psycopg2-binary

Resolved 116 packages in 168ms
░░░░░░░░░░░░░░░░░░░░ [0/1] Installing wheels...                                 warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 1 package in 717ms13
 + psycopg2-binary==2.9.13

In [14]:
from sqlalchemy import create_engine
engine = create_engine('postgresql+psycopg://root:root@localhost:5432/ny_taxi')

In [15]:
print(pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine))

CREATE TABLE yellow_taxi_data (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [20]:
df.head(n=0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')

0

In [19]:
df.head(0)

Empty DataFrame
Columns: [VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, RatecodeID, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge]
Index: []

In [25]:
len(df)

1369765

In [27]:
df_iter = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates,
    iterator=True,
    chunksize=100000,
)

In [32]:
df=next(df_iter)

In [33]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
200000,2,2021-01-06 17:09:54,2021-01-06 17:30:53,1,2.78,1,N,232,97,1,14.0,1.0,0.5,2.75,0.00,0.3,18.55,0.0
200001,2,2021-01-06 17:52:35,2021-01-06 17:55:39,1,0.62,1,N,170,107,2,4.5,1.0,0.5,0.00,0.00,0.3,8.80,2.5
200002,2,2021-01-06 17:21:30,2021-01-06 17:26:34,1,0.66,1,N,239,238,1,5.5,1.0,0.5,0.50,0.00,0.3,10.30,2.5
200003,2,2021-01-06 17:47:53,2021-01-06 18:15:45,1,6.94,1,N,170,40,2,23.0,1.0,0.5,0.00,0.00,0.3,27.30,2.5
200004,2,2021-01-06 17:33:48,2021-01-06 18:17:16,1,18.46,2,N,132,163,1,52.0,4.5,0.5,13.18,6.12,0.3,79.10,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299995,2,2021-01-08 21:42:00,2021-01-08 21:46:40,1,1.11,1,N,263,263,1,6.0,0.5,0.5,2.94,0.00,0.3,12.74,2.5
299996,2,2021-01-08 21:53:04,2021-01-08 22:03:00,1,4.66,1,N,141,4,1,14.5,0.5,0.5,3.66,0.00,0.3,21.96,2.5
299997,2,2021-01-08 21:16:14,2021-01-08 21:26:11,1,1.60,1,N,113,4,2,8.5,0.5,0.5,0.00,0.00,0.3,12.30,2.5
299998,2,2021-01-08 21:46:01,2021-01-08 21:53:24,1,1.32,1,N,141,163,1,7.0,0.5,0.5,1.30,0.00,0.3,12.10,2.5
299999,2,2021-01-08 21:27:58,2021-01-08 21:35:19,1,2.37,1,N,264,223,1,9.0,0.5,0.5,2.06,0.00,0.3,12.36,0.0

In [34]:
!uv add tqdm

Resolved 117 packages in 686ms
░░░░░░░░░░░░░░░░░░░░ [0/1] Installing wheels...                                 warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 1 package in 31ms
 + tqdm==4.70.1

In [35]:
from tqdm import tqdm

In [ ]:
for df_chunk in tqdm(df_iter):
    df_chunk.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

2it [00:27, 13.96s/it]